steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-service', '.']
    dir: 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-service']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'backend-service',
      '--image', 'gcr.io/$PROJECT_ID/backend-service',
      '--timeout', '1000s', '--port', '5000',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
    ]

options:
  logging: CLOUD_LOGGING_ONLY
